"""Golden signing tests — byte parity with the live Temporal signer fixture.

The fixture (golden_temporal_signed_request.json) was generated by EXECUTING
the Temporal SDK's request_signing.py with injected timestamp+nonce. These
tests prove the base SDK reproduces the signed request byte-for-byte.
"""

from __future__ import annotations

import base64
import hashlib
import json
import pathlib
import re

from openbox_core.identity import (
    EMPTY_BODY_SHA256,
    AgentIdentity,
    build_canonical_string,
    prepare_signed_request,
)
from openbox_core.serialization import serialize_body

FIXTURE = json.loads(
    (pathlib.Path(__file__).parent / "golden_temporal_signed_request.json").read_text()
)


def golden_identity() -> AgentIdentity:
    return AgentIdentity.from_private_key(FIXTURE["agent_did"], FIXTURE["seed_b64"])


def sign_golden() -> tuple[dict, bytes]:
    return prepare_signed_request(
        FIXTURE["method"],
        FIXTURE["path"],
        FIXTURE["payload"],
        api_key=FIXTURE["api_key"],
        identity=golden_identity(),
        _timestamp=FIXTURE["timestamp"],
        _nonce=FIXTURE["nonce"],
    )


class TestGoldenByteParity:
    def test_body_bytes_match_exactly(self):
        _, body = sign_golden()
        assert body == base64.b64decode(FIXTURE["body_b64"])

    def test_body_hash_is_sha256_of_transmitted_bytes(self):
        headers, body = sign_golden()
        assert hashlib.sha256(body).hexdigest() == FIXTURE["body_sha256"]
        assert headers["X-OpenBox-Body-SHA256"] == FIXTURE["body_sha256"]

    def test_canonical_string_matches(self):
        canonical = build_canonical_string(
            FIXTURE["method"],
            FIXTURE["path"],
            FIXTURE["timestamp"],
            FIXTURE["nonce"],
            FIXTURE["body_sha256"],
        )
        assert canonical == FIXTURE["canonical"]

    def test_signature_matches_temporal_signer(self):
        headers, _ = sign_golden()
        assert (
            headers["X-OpenBox-Agent-Signature"]
            == FIXTURE["signed_headers"]["X-OpenBox-Agent-Signature"]
        )

    def test_all_signed_headers_match(self):
        headers, _ = sign_golden()
        for name, expected in FIXTURE["signed_headers"].items():
            assert headers[name] == expected, f"header {name} diverged"

    def test_signature_is_padded_std_base64(self):
        headers, _ = sign_golden()
        sig = headers["X-OpenBox-Agent-Signature"]
        # std alphabet incl. + and /, padded — never urlsafe
        assert re.fullmatch(r"[A-Za-z0-9+/]+={0,2}", sig)
        assert len(base64.b64decode(sig, validate=True)) == 64  # Ed25519 sig size


class TestSigningContractInvariants:
    def test_signing_timestamp_keeps_offset_never_z(self):
        # The TIMESTAMP trap: signing keeps +00:00; event payloads use Z.
        assert FIXTURE["timestamp"].endswith("+00:00")
        headers, _ = sign_golden()
        assert headers["X-OpenBox-Agent-Timestamp"].endswith("+00:00")
        assert not headers["X-OpenBox-Agent-Timestamp"].endswith("Z")

    def test_path_includes_api_v1_prefix(self):
        assert FIXTURE["path"].startswith("/api/v1/")
        assert FIXTURE["canonical"].split("\n")[1] == FIXTURE["path"]

    def test_empty_body_hash_constant(self):
        assert hashlib.sha256(b"").hexdigest() == EMPTY_BODY_SHA256
        assert FIXTURE["empty_body_sha256"] == EMPTY_BODY_SHA256

    def test_none_payload_serializes_to_empty_bytes(self):
        headers, body = prepare_signed_request(
            "GET",
            "/api/v1/auth/validate",
            None,
            api_key=FIXTURE["api_key"],
            identity=golden_identity(),
            _timestamp=FIXTURE["timestamp"],
            _nonce=FIXTURE["nonce"],
        )
        assert body == b""
        assert headers["X-OpenBox-Body-SHA256"] == EMPTY_BODY_SHA256

    def test_compact_separators_no_spaces(self):
        body = serialize_body({"a": 1, "b": [1, 2]})
        assert body == b'{"a":1,"b":[1,2]}'

    def test_unsigned_mode_omits_aip_headers(self):
        headers, _ = prepare_signed_request(
            "POST", FIXTURE["path"], {"x": 1}, api_key=FIXTURE["api_key"], identity=None
        )
        assert not any(h.startswith("X-OpenBox-Agent") for h in headers)
        assert headers["Authorization"] == f"Bearer {FIXTURE['api_key']}"


class TestCrewAIDivergenceDocumented:
    """The CrewAI SDK signer diverges (aip_signing.py:70-71): it rewrites the
    timestamp +00:00 -> Z and uses uuid4() nonces. The base SDK matches
    TEMPORAL. This test documents the divergence — it does NOT unify them."""

    def test_crewai_style_timestamp_produces_different_signed_bytes(self):
        identity = golden_identity()
        crewai_style_timestamp = FIXTURE["timestamp"].replace("+00:00", "Z")
        assert crewai_style_timestamp != FIXTURE["timestamp"]

        temporal_canonical = FIXTURE["canonical"]
        crewai_canonical = build_canonical_string(
            FIXTURE["method"],
            FIXTURE["path"],
            crewai_style_timestamp,
            FIXTURE["nonce"],
            FIXTURE["body_sha256"],
        )
        assert crewai_canonical != temporal_canonical
        assert identity.sign(crewai_canonical) != identity.sign(temporal_canonical)


class TestNoJsonKwargInClient:
    def test_client_never_uses_httpx_json_kwarg(self):
        # Re-serializing with json= breaks Core's body-hash verification.
        # AST-based: docstrings legitimately WARN about json=, so plain grep
        # would false-positive; only real call keywords count.
        import ast

        source = pathlib.Path("openbox_core/client.py").read_text()
        offenders = [
            node.lineno
            for node in ast.walk(ast.parse(source))
            if isinstance(node, ast.Call)
            for kw in node.keywords
            if kw.arg == "json"
        ]
        assert offenders == [], (
            f"client.py passes json= at lines {offenders} — must send "
            "content=body_bytes (re-serialization breaks the signed body hash)"
        )
